import { HEALTHY_RESULT_BASE } from '../constants';
import { SchoolInfo } from './searchSchool';
import { apiPostRequest } from '../request';
import { GetUserInfoResponse } from './passwordLogin';

export async function sendSurvey(
  token: string,
  { userNameEncpt }: GetUserInfoResponse,
  info: SchoolInfo
) {
  const { data } = await surveyApi(token, userNameEncpt, info);
  return data;
}

function surveyApi(token: string, username: string, { baseURL }: SchoolInfo) {
  return apiPostRequest<SendSurveyRequest, SurveyResponse>(
    '/registerServey', // API 이름 유의 !! Servey임
    { ...HEALTHY_RESULT_BASE, upperToken: token, upperUserNameEncpt: username },
    { baseURL, token }
  );
}

export type SurveyResponse = {
  registerDtm: string;
  inveYmd: string;
};
// Generated by https://quicktype.io
export interface SendSurveyRequest {
  rspns01: string;
  rspns02: string;
  rspns03: null;
  rspns04: null;
  rspns05: null;
  rspns06: null;
  rspns07: string;
  rspns08: string;
  rspns09: string;
  rspns10: null;
  rspns11: null;
  rspns12: null;
  rspns13: null;
  rspns14: null;
  rspns15: null;
  rspns00: string;
  deviceUuid: string;
  upperToken: string;
  upperUserNameEncpt: string;
}
